const projects={
 pause:{title:'PauseBeforeBuy',meta:'PRODUCT EXPLORATION · 2026.08 — PRESENT',body:`<h3>Start with a real hesitation. / 从一个真实的犹豫开始</h3><p>The concept focuses on impulse purchases: collecting a user’s question, retrieving relevant information, showing evidence, and explaining a buy-or-pause suggestion. The user makes the final decision.</p><p lang="zh">我设计了“用户输入—信息检索—证据呈现—二分类判断—购买或暂缓建议”的产品路径。希望用户能看见理由，而不是只收到一个结论。</p><h3>Designing the limits / 把边界也设计进去</h3><p>Ten test scenarios have been designed, including missing information, unusual charges, zero savings and contradictory inputs. Checking calculation accuracy, explanations and risk notices is planned; this is not a claim that all tests have passed.</p><p lang="zh">已制定十个测试场景，计划核对计算准确性、解释依据和风险提示完整性。使用模拟或匿名数据，不连接银行或支付账户。</p><h3>What comes next / 接下来</h3><p>Validate the decision flow and strengthen the evidence behind each suggestion before expanding the idea. Financial education and voluntary giving remain longer-term ambitions.</p><p lang="zh">先验证决策流程，再讨论更广泛的财务教育与自愿公益功能。当前仍是探索中的项目。</p>`},
 automation:{title:'Making routine work flow.',meta:'UIPATH · LEARNING PROJECTS · 2026.08 — PRESENT',body:`<h3>Connected workflows / 连接起来的工作流</h3><p>I connected an email workflow with an appointment workflow. The first reads simulated messages from Google Sheets and calls an agent; the second supports record lookup, changes and deletion as a tool, returning results and logs.</p><p lang="zh">邮件工作流读取模拟来信并调用 Agent；预约工作流负责记录查询、修改与删除，并返回处理结果、记录日志。</p><h3>Finance application / 财务应用</h3><p>A separate invoice-entry workflow divides the process into reading data, validating fields, entering records and notifying results. Exception handling, human review and traceability are part of the design.</p><p lang="zh">将发票录入拆成清晰步骤，并为异常识别、人工复核和操作留痕预留机制。这是学习与原型实践，未宣称企业级部署或已实现的效率收益。</p>`},
 research:{title:'Systems need people, too.',meta:'RESEARCH & CAMPUS EXPERIENCE · 2023–2025',body:`<h3>Manufacturing relocation research / 制造产业转移研究</h3><p>As a research assistant on a provincial project in 2024–2025, I supported literature work and decision modelling, using approaches including multiple regression and fuzzy comprehensive evaluation to explore relocation factors and risks.</p><p lang="zh">参与“新发展格局下辽宁制造产业转移路径研究”，协助导师开展产业转移决策模型与风险分析工作，把理论、数据与实际问题连接起来。</p><h3>Making collaboration happen / 让协作真正发生</h3><p>As secretary-general and vice president of a campus association from November 2023 to June 2025, I coordinated publicity and new-media teams and helped organise more than ten themed events.</p><p lang="zh">组织活动不仅是分配任务，也需要把目标说清楚，关心不同成员的节奏，并把细节一项项落实。</p>`}
};
const dialog=document.querySelector('#project-dialog');
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=projects[b.dataset.project];document.querySelector('#dialog-content').innerHTML=`<span class="dialog-meta">${p.meta}</span><h2 id="dialog-title">${p.title}</h2>${p.body}`;dialog.showModal();dialog.scrollTop=0}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),avatar=document.querySelector('#avatar'),motionButton=document.querySelector('#motion-toggle');let userPaused=false;let active=[];
function isReduced(){return reduce.matches||userPaused}
function stop(){active.forEach(a=>a.cancel());active=[]}
function sync(){stop();document.body.classList.toggle('motion-off',isReduced());motionButton.setAttribute('aria-pressed',String(isReduced()));motionButton.textContent=isReduced()?'Motion off / 动效关闭':'Motion on / 动效开启';document.querySelector('#replay').disabled=isReduced();document.querySelector('#replay').title=isReduced()?'Animation is disabled by your motion preference / 动效已关闭':''}
function greet(){if(isReduced())return;stop();const scale=innerWidth<768?1.18:1.48;active.push(avatar.animate([{transform:'translate3d(0,0,0) scale(1) rotate(0deg)',offset:0},{transform:`translate3d(0,-22px,0) scale(${scale}) rotate(-3deg)`,offset:.22},{transform:`translate3d(0,-22px,0) scale(${scale}) rotate(3deg)`,offset:.32},{transform:`translate3d(0,-22px,0) scale(${scale}) rotate(-2deg)`,offset:.42},{transform:`translate3d(0,-22px,0) scale(${scale}) rotate(0deg)`,offset:.48},{transform:`translate3d(0,-22px,0) scale(${scale}) rotate(0deg)`,offset:.67},{transform:'translate3d(0,0,0) scale(1) rotate(0deg)',offset:1}],{duration:5200,easing:'cubic-bezier(.22,.61,.36,1)',fill:'none'}))}
motionButton.addEventListener('click',()=>{userPaused=!userPaused;sync()});reduce.addEventListener('change',sync);document.querySelector('#replay').addEventListener('click',greet);sync();
const avatarImg=avatar.querySelector('img');if(avatarImg.complete){setTimeout(greet,450)}else avatarImg.addEventListener('load',()=>setTimeout(greet,450),{once:true});
